name: Excavator

on:
  schedule:
    - cron: '0 */6 * * *' # Every 6 hours
  workflow_dispatch:

jobs:
  excavate:
    name: Auto-update manifests
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Excavator
        uses: ScoopInstaller/GithubActions@main
        env:
          GITH: ${{ secrets.GITHUB_TOKEN }}
          SKIP_UPDATED: 1
